### ISSUE TITLE
error: espcomm_upload_mem failed

### ISSUE THREAD

**Issue by zachJsmith** [CharlesJGantt/LinkNode-R4-Controlled-By-Amazon-Alexa#4]
Im not very good at programming and im only 12 (also i used this to upload it https://www.amazon.com/gp/product/B012YUANZK/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1)  when i try to upload it to the r4 it says this:

Arduino: 1.8.2 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, 40MHz, QIO, 115200, 512K (64K SPIFFS), ck, Disabled, None"

Archiving built core (caching) in: /var/folders/0s/tcclhfjs2p92xhrr0yd0ryx40000gn/T/arduino_cache_110302/core/core_esp8266_esp8266_generic_CpuFrequency_80,FlashFreq_40,FlashMode_qio,UploadSpeed_115200,FlashSize_512K64,ResetMethod_ck,Debug_Disabled,DebugLevel_None_____c705db4fc699f6463c021fb2c3716b5a.a
Sketch uses 249701 bytes (57%) of program storage space. Maximum is 434160 bytes.
Global variables use 37500 bytes (45%) of dynamic memory, leaving 44420 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by zachJsmith** [comment]
also i have tried unplugging everything and re-uploading everything many times

**Comment by nizamaj** [comment]
Check your wiring on FTDI USB to UART Cable to LinkNode ( it should be RX to TX & TX to RX- crossover) and jumpber should be set to programing mode also you need to connect to power source ( 5V 2amp) if everything correct it should flash .

**Comment by nizamaj** [comment]
Check your FTDI USB to UART Cable to LinkNode (cable TX to RX & RX to TX - crossover ) and the power source should connect ( 5V 2Amp)  and the jumper should set to programming mode , if everything OK then it should flash 



![211201004-diagram](https://cloud.githubusercontent.com/assets/21243601/25306215/82d37948-2791-11e7-9487-73e80d1ab8d2.jpg)

**Comment by CharlesJGantt** [comment]
I get this issue as well when programming any ESP8266 device with the Arduino IDE, and it seems to be a common intermittent issue if you search the Arduino forums and stack exchange. What nizamaj suggested has fixed it for me in the past but the issue always comes back. I find it best to just unplug the programming cable, close the IDE, and then reconnect the cable, open the IDE and try to upload again. Closing this issue for now.
